### Get users info
GET http://127.0.0.1:8000/auth/users/me/


### Create Tokens
POST http://127.0.0.1:8000/auth/jwt/create/



### Create New users
POST http://127.0.0.1:8000/auth/users/


### Verify Tokens
POST http://127.0.0.1:8000/auth/jwt/verify/


###
GET http://127.0.0.1:8000/api/products/